In [1]:
import numpy

In [2]:
array = numpy.array([1,2,3,4])

In [3]:
print(array)

[1 2 3 4]


In [4]:
import numpy as np

In [5]:
array = np.array([1,2,3,4])

In [6]:
print(array)

[1 2 3 4]


In [10]:
ar=np.arange(5)

In [11]:
print(ar)

[0 1 2 3 4]


In [7]:
from numpy import array

In [8]:
array=array([1,2,3,4])

In [9]:
print(array)

[1 2 3 4]


In [12]:
import numpy as np

In [13]:
np.random.randint(2,10)

9

In [14]:
from numpy.random import randint

In [15]:
randint(2,10)

3

In [16]:
print(np.__version__)

1.19.2


In [17]:
sample=np.random.randint(0,100,20000000)

In [18]:
%timeit np.power(sample,2)

44.9 ms ± 721 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit list(np.power(sample,2))

1.4 s ± 34.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
