# Dimensions

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
type(arr)

numpy.ndarray

In [5]:
a=np.array(12)
print(a.ndim)

0


In [6]:
a=np.array([1,2,3,4])
print(a.ndim)

1


In [7]:
a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [8]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)

3


In [9]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


# *Shape*

In [10]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c.ndim)

2


In [11]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c.shape)

(2, 4)


In [12]:
a=np.array([[1,2,3],[4,5,6]])

a.shape=(3,2)

In [13]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

b=a.reshape(2,3,2)

In [15]:
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
print(b.ndim)

3


In [17]:
arr=a.reshape(-1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# *Size*

In [18]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [19]:
arr.itemsize

4

In [20]:
print(arr.itemsize)

4


In [21]:
arr=np.array([1,2,3,4,5],dtype='int16')
print(arr.dtype)

int16


In [22]:
arr.itemsize

2

In [23]:
print(arr.size*arr.itemsize)

10


In [24]:
arr=np.array([1,2,3,4,5],dtype='i1')
print(arr.dtype)

int8


In [25]:
arr=np.array([1,2,3,4,5],dtype='f2')
print(arr.dtype)

float16


In [26]:
arr=np.array([1,2,3,4,5],dtype='complex')
print(arr.dtype)

complex128


In [27]:
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [28]:
arr=np.array([1.1,2.2,3.3])

cv=arr.astype('i')
print(cv)

[1 2 3]
