# name[<span style='color:Green'>start</span>:<span style='color:Red'>stop</span>:<span style='color:Blue'>step</span>]<br>
 .Index<br>
 .Slice<br>

In [1]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [7]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])

2


In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[0,1]

2

In [9]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[0,1,2]

6

In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[1,-1]

10

In [11]:
arr=np.array([1,2,3,4,5])
arr[1:3]

array([2, 3])

In [12]:
arr[4:]

array([5])

In [13]:
arr=np.array([1,2,3,4,5,6,7])
arr[4:]

array([5, 6, 7])

In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[:,4]

array([ 5, 10])

In [15]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr[0,:]

array([1, 2, 3, 4, 5])

In [18]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[0, 1:6:2]

array([2, 4, 6])

In [19]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[0,2]=2000

In [20]:
arr

array([[   1,    2, 2000,    4,    5,    6,    7,    8],
       [   6,    7,    8,    9,   10,   11,   12,   13]])

In [21]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[0,1:4]=3000

In [22]:
arr

array([[   1, 3000, 3000, 3000,    5,    6,    7,    8],
       [   6,    7,    8,    9,   10,   11,   12,   13]])

In [23]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[:,2]=[3000,4000]

In [24]:
arr

array([[   1,    2, 3000,    4,    5,    6,    7,    8],
       [   6,    7, 4000,    9,   10,   11,   12,   13]])

In [25]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[0,1,2]

6

In [29]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[:, 1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [30]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[:, 1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [31]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[:, 1,:1]

array([[ 4],
       [10]])

In [32]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[:, 1,:0]

array([], shape=(2, 0), dtype=int32)

In [33]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr[:, 1,:]=[[9,9,9],[8,8,8]]

In [34]:
arr

array([[[1, 2, 3],
        [9, 9, 9]],

       [[7, 8, 9],
        [8, 8, 8]]])

In [35]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr[:,]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[:4]

array([1, 2, 3, 4])

In [39]:
arr=np.array([1,2,3,4,5])
arr[-3:-1]

array([3, 4])

In [40]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[-3:-1]

array([6, 7])

In [41]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[1:5:2]

array([2, 4])

In [42]:
arr=np.array([1,2,3,4,5,6,7,8])
arr[::2]

array([1, 3, 5, 7])

In [43]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[1,1:4]

array([7, 8, 9])

In [44]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[0:2,2]

array([3, 8])

In [45]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[0:1,2:4]

array([[3, 4]])

In [46]:
arr=np.array([[1,2,3,4,5,6,7,8],[6,7,8,9,10,11,12,13]])
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y=arr[1:4,[1,2]]

In [49]:
y

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [50]:
arr=[arr>5]

In [51]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [52]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [57]:
a=np.array([np.nan,1,2,np.nan,3,4,5])
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [59]:
a=np.array([2+6j,1,2,5+5j,3,4,5])
a[np.iscomplex(a)]

array([2.+6.j, 5.+5.j])